<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <AssemblyName>hidmaestro_host</AssemblyName>
    <ApplicationIcon>logo-light.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="HIDMaestro.Core">
      <HintPath>..\..\bin\HIDMaestro.Core.amd64.dll</HintPath>
      <Private>false</Private>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Reference>
  </ItemGroup>

</Project>
